version: "2"
services:
  rundeck:
    # image: huyntt/rundeck
    build: .
    restart: unless-stopped
    container_name: rundeck
    hostname: localhost
    environment:
      RUNDECK_GRAILS_URL: 'http://localhost:4440'
      RUNDECK_SERVER_FORWARDED: 'true'
    ports:
      - "4440:4440"
    volumes:
      - data:/home/rundeck/server/data
      - data:/configs:/home/rundeck/configs
      - ./realm.properties:/home/rundeck/server/config/realm.properties
      - ./resouces.yaml:/home/rundeck/resouces.yaml
      - ./resouces-win.yaml:/home/rundeck/resouces-win.yaml
volumes:
  data:
    name: data